version: "3.9"

services:
  leader:
    build: .
    container_name: leader
    environment:
      - NODE_ROLE=leader
      - PORT=5000
      - WRITE_QUORUM=${WRITE_QUORUM:-3}
      - MIN_DELAY_MS=0
      - MAX_DELAY_MS=1000
      - FOLLOWER_URLS=http://f1:5000,http://f2:5000,http://f3:5000,http://f4:5000,http://f5:5000
    ports:
      - "5000:5000"
    depends_on:
      - f1
      - f2
      - f3
      - f4
      - f5

  f1:
    build: .
    container_name: f1
    environment:
      - NODE_ROLE=follower
      - PORT=5000
    ports:
      - "5001:5000"

  f2:
    build: .
    container_name: f2
    environment:
      - NODE_ROLE=follower
      - PORT=5000
    ports:
      - "5002:5000"

  f3:
    build: .
    container_name: f3
    environment:
      - NODE_ROLE=follower
      - PORT=5000
    ports:
      - "5003:5000"

  f4:
    build: .
    container_name: f4
    environment:
      - NODE_ROLE=follower
      - PORT=5000
    ports:
      - "5004:5000"

  f5:
    build: .
    container_name: f5
    environment:
      - NODE_ROLE=follower
      - PORT=5000
    ports:
      - "5005:5000"

